### ISSUE TITLE
Les administrateurs ne peuvent créer qu'une seule démocratie

### ISSUE THREAD

**Issue by florent-andre** [democracy-os-fr/democracyos#1]
Bonjour,
C'est florent, nous nous sommes rencontrés lors du workshop d'install de democracios, où j'ai fait une installation pour openlaw.fr

Je viens de me rendre compte qu'il n'est possible en admin de ne créer qu'une seulle nouvelle démocratie.
En effet après la création de la première il n'y a plus de bouton "create" et l'utilisation du lien direct de création (/forums/new) renvoi vers la page d'accueil (sans logs particuliers).

je suis sur la branche 
os2/alt/fr
au commit affff9a58144d59e89c4c4d939854df17e3e662e

++

**Comment by virgile-dev** [comment]
Bonjour Florent, 

On travaille sur un fix pour notre prochaine release fin février début mars. On te tient au courant dès que ça sort. Merci d'avoir pris le temps de nous écrire une issue.

Bonne journée!

**Comment by florent-andre** [comment]
Merci.
Des nouvelles pour la release ?

**Comment by virgile-dev** [comment]
@florent-andre on a bien avancé oui, je laisse @moustachu t'indiquer la branche et les dossiers qu'ils faut que tu check pour voir le code qui a été modifié.
