### ISSUE TITLE
[Alt-Agora] mauvaise compréhension par les utilisateurs de la fonctionnalité up/downvote

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#11]
Avec Pierre-Louis on est pas sûres que les gens comprennent bien : 
<img width="237" alt="capture d ecran 2016-05-08 a 11 10 54" src="https://cloud.githubusercontent.com/assets/11473995/15096968/8dc9f652-150d-11e6-8fd9-309a934eae51.png">
<img width="202" alt="capture d ecran 2016-05-08 a 11 09 23" src="https://cloud.githubusercontent.com/assets/11473995/15096969/8fe42cbe-150d-11e6-896c-3af82a9d57d8.png">

Je propose de tester avec les emoji ``Thumbs-up`` ``Thumbs-down``
![thumbs-up black](https://cloud.githubusercontent.com/assets/11473995/15097016/17019e10-150f-11e6-9a95-c33f84215b4a.png)
![thumbs-up](https://cloud.githubusercontent.com/assets/11473995/15097013/f373024a-150e-11e6-94ee-4d31ddeab025.png)

@moustachu t'en penses quoi?

**Comment by valentinchaput** [comment]
Je confirme que c'est une demande pertinente, les flèches n'étant pas assez explicites pour ceux qui n'ont pas les codes de Reddit

**Comment by virgile-dev** [comment]
Je viens de tomber sur ce module qui est assez sympa : http://kapermolen.hasselt.be/posts/PhGyrqeyadCzxijbW/kapermolen-sportpark
<img width="125" alt="capture d ecran 2016-05-23 a 11 05 54" src="https://cloud.githubusercontent.com/assets/11473995/15465731/680b4428-20d6-11e6-8009-b25fd00bf1dd.png">

@moustachu qu'est-ce que t'en penses?

**Comment by virgile-dev** [comment]
Je rajoute le tag ``help wanted`` pour voir si quelqu'un de la communauté se motive pour faire le test

**Comment by virgile-dev** [comment]
Nouveau brief pour cette issue. Après avoir sondé 4 participants au hackathon ODN deux choses ressortent : 
- A l'unanimité les pouces haut bas leurs parraissent plus clair que les flèches et + / - 
- Le score de l'argument est notion qui leur paraît ne pas refléter bien l'adhésion à l'argument. C'est un métrique intéressante pour classer le flux d'argument mais comme métrique pour l'utilisateur c'est pas informatif. Un argument qui a reçu 50 upvotes et 50 downvote au un score de 0, alors qu'un argument qui reçoit 5 upvotes et 0 downvotes serait placé au dessus. Ce serait plus intéressant de montrer à côté des pouces le nombre de hits.

Ce qui nous amène à la création deux nouveaux filtres : 
- ``les plus upvotés``
- ``les plus downvotés``

Voilà un petit mockup : 
![contributions](https://cloud.githubusercontent.com/assets/11473995/15985272/360a4e4e-2fe8-11e6-8966-019e5c12acec.png)

**Comment by virgile-dev** [comment]
C'est cool avec les pouces mais un peu petit : 
<img width="679" alt="capture d ecran 2016-06-14 a 18 40 31" src="https://cloud.githubusercontent.com/assets/11473995/16051469/46f4a126-3260-11e6-8222-7d7f99444377.png">

**Comment by moustachu** [comment]
@virgile-dev es-tu satisfait du dev actuel ? 

![image](https://cloud.githubusercontent.com/assets/464350/18279696/bf9d923a-7456-11e6-8e5c-1f8c6577a4cb.png)

Si oui on **close**

**Comment by virgile-dev** [comment]
Yes merci!
