### ISSUE TITLE
Switch Logo --> Organisation Name

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#14]
Récupérer les devs pour que quand aucun ``logo`` n'est spécifié dans les variables de configuration l'application le remplace par l' ``organisation name``

**Comment by moustachu** [comment]
@virgile-dev 
**à tester** sur http://dos-agora-demo.herokuapp.com/admin/tags

Le nouveau fonctionnement est :
- les variables `logo` et `logoMobile` sont renseignée par défaut (cf `config/defaults.json`)
- elles peuvent comme avant être surchargées avec un fichier de conf ou une variable d'environnement
- **si** la variable `logo` est surchargée avec la valeur null ou "" (chaine vide) **alors** c'est la valeur de `organizationName` qui sera utilisé en mode logo titre
