### ISSUE TITLE
[Alt-Agora] fix pour multiforum = false

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#16]
- Changer la page par défaut admin /forums --> /topics

**Comment by virgile-dev** [comment]
@moustachu tu penses pouvoir gérer ce cas pour la release? pas mal de gens souhaitent utiliser DOS en forum simple ce serait cool qu'il puissent le faire avec tous les nouveaux features.

**Comment by moustachu** [comment]
@virgile-dev à tester
