### ISSUE TITLE
[Alt Agora] Le formulaire d'inscription de cette version n'est pas générique

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#18]
Je sais qu'on peut modifier les valeurs des champs grâce à du json mais peut-on par défaut remettre le formulaire de base de Democracy OS.

Question bête est-ce qu'on pourrait activer le formulaire actuel quand du json est envoyé dans ``règle`` ?

**Comment by moustachu** [comment]
**à tester** [ici](https://dos-agora-demo.herokuapp.com/signup)

En l'état les informations supplémentaires des formulaires utilisateurs ( signup & profile ) sont mes suivantes : 
- **Age** : ce champ n'est pas lié aux règles, ses valeurs sont donc _bloquées_ et stockées dans les fichiers de traductions. Il est activable via la variable de configuration `userAge` ( `true` / `false` )
- **Quartier** : les valeurs possibles sont à ajouter en tant que règles via l'interface d'admin et il le type de règle s'active en mettant la valeur `location` dans la variable de configuration `rules` ( ex : `"rules": ["role","location"]` )
- **Activité** : les valeurs possibles sont à ajouter en tant que règles via l'interface d'admin et il le type de règle s'active en mettant la valeur `activity` dans la variable de configuration `rules` ( ex : `"rules": ["activity","location"]` )
