### ISSUE TITLE
[alt-agora] la page d'aide à la mise en forme (markdown) a disparu

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#22]
Bug observable sur http://dos-agora-demo.herokuapp.com/help/markdown

**Comment by moustachu** [comment]
Bug d'affichage corrigé mais j'ai désactivé les liens vers la page en question car l'éditeur de texte des commentaires / contributions est passé en mode Wysiwig (Medium Editor) 👍
