### ISSUE TITLE
Supprimer ou fermer une démocracie d'un utilisateur

### ISSUE THREAD

**Issue by florent-andre** [democracy-os-fr/democracyos#3]
Bonjour,

Comment je peux faire avec un compte administrateur pour "fermer" ou "supprimer" une démocracie créé par un utilisateur ? 

J'ai cherché dans l'interface mais n'ai vu l'option nul part...

Sinon une ligne de commande ? 

Thanks.

**Comment by virgile-dev** [comment]
Salut @florent-andre,
Est-ce que @moustachu a répondu à ta question pendant le hackathon?
Bonne journée, 
Virgile

**Comment by florent-andre** [comment]
ca à l'air maintenant bon avec un version récente.
thanks.
