### ISSUE TITLE
Traduire le site de documentation docs.democracyos.org

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#31]
Des volontaires pour nous aider à traduire le site de documentation de DemocracyOS de l'anglais vers le français? 

**Voici la méthode de travail que nous proposons :** 

Le rendu de la documentation se trouve ici :
http://docs.democracyos.org
Les fichiers sources au format Markdown sont ici :
https://github.com/DemocracyOS/democracyos/tree/master/docs

le code HTML du site se génère à partir de ces fichiers

A priori, il est plus rapide de modifier directement les fichiers anglais au fur et à mesure pour avoir directement accés à la source de trad et au formatage.

2 options : 

- soit vous récuperez le dossier et vous organisez  pour faire l'édition collaborative (sur framasheet ou drive)
- soit vous éditez directement les fichiers sur notre fork français de DemocracyOS chez github (et je peux vous faire une branche dédiée pendant la phase de traduction)

Dans les 2 cas, il faudra donc générer le code HTML pour visualiser le rendu final
avec un outil de visualisation markdown comme dillinger.io
en éditant directement les fichiers sur github

Au final, il faudra de toute façon finir par publier sur github pour générer un site complet via ReadTheDocs.org (c'est une version qui date un peu, je la mettrais à jour si besoin).

Dans un second temps, on verra avec la team argentine pour une publication sur docs.democracyos.org dans une section FR 
à vous de jouer !

Merci d'avance!

**Comment by Farocs** [comment]
Je peux aider à la traduction (a première vu il y a pas un volume énorme non plus ...)

**Comment by Mowgli-cc** [comment]
Super merci! En effet le volume n'est pas énorme, on peut le faire rapidement si on s'y met à plusieurs. Si tu es dispo les 10 et 11 juin, on organise un [hackathon](http://opendemocracynow.net/Hackathon_liste/Hackathon3.html) à la fondation Mozilla dont un des ateliers sera consacré à DemocracyOS. Ca peut donc être l'occasion de le faire ensemble.
Sinon, on procède différement :)

**Comment by Farocs** [comment]
Alors n'étant pas Parisien (cela arrive) c'est un peu dur d'être à tous ses rendez-vous (parfois un peu frustrant d'ailleurs) ...

Maintenant, si vous faite une branche sur le github, on commence en asynchrone et vous ferez la lecture/finition au hackathon si vous voulez :)
