### ISSUE TITLE
[alt-agora] les + et - de upvote downvote ne garde pas la couleur une fois voté

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#35]
C'est pas très pratique pour savoir sur quels arguments on a voté ensuite. Reprendre le fonctionnement d'origine SVP.

**Comment by moustachu** [comment]
merci de donner d'avantage de précision lors de la saisie de ticket @virgile-dev ...

Parce que là, j'ai oublié comment c'était avant, donc je vais devoir trouver une vieille version et faire le test moi-même ...

**Comment by virgile-dev** [comment]
Dans les anciennes versions quand on votait sur un argument la petite flèche gardait la couleur et permettait de voir les arguments sur lesquels on avait voté. @moustachu 
![image](https://cloud.githubusercontent.com/assets/11473995/15986720/91ac118e-300f-11e6-9816-4b87806bbf35.png)
![image](https://cloud.githubusercontent.com/assets/11473995/15986722/9b2016e8-300f-11e6-949e-d1d4a30a5bb7.png)
