### ISSUE TITLE
Ajouter un bouton d'action aux `forum-card`

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#5]
Avec la nouvelle version `agora` j'ai remarqué qu'il nétait pas évident pour les utilisateurs qu'il fallait cliquer sur les `forum-card` pour participer aux débats du forum. 

Je serais d'avis de tester l'ajout d'un bouton `Participer à ce forum` pourrait améliorer substantiellement l'expérience des utilisateurs. 
![cta forum-card2](https://cloud.githubusercontent.com/assets/11473995/14598683/c7ea0382-0553-11e6-8b65-465a14a819ae.png)
![cta forum-card](https://cloud.githubusercontent.com/assets/11473995/14598684/c7ef8d3e-0553-11e6-947f-7dcc670660da.png)
@moustachu  t'en penses quoi?

**Comment by moustachu** [comment]
Je valide le bouton !

La discussion étant lancée, je pense aussi rajouter quelques stats rapides (max 3). 
Il faudrait choisir celles qui pourraient être pertinentes dans la liste ci-dessous : 

- nombre de débats total
- nombre de débats ouverts
- nombre de débats clos
- nombre de participants cumulés
- nombre de contributions / commentaires / réponses

si on prend en compte l'utilisateur courant, on peut aussi prendre en compte : 

- nombre de débats ouverts non votés

Quoi qu'il en soit, je rajouterais le bouton dès que possible

**Comment by virgile-dev** [comment]
M'est avis que rajouter des stats à cet endroit est pas archi prioritaire et chargerait l'UI. En revanche oui rajouté des stats pour l'admin sur chaque `forum` puis `débat` et pas seulement par instance mais c'est un autre ticket. Mais à choisir je partirais sur 2 : `Nombre de débats`  et `Nombre de participants`

@arhur-koenig  @valentinchaput vous en pensez

**Comment by valentinchaput** [comment]
On peut avoir une transformation des stats call to action "rejoignez 42 participants sur 8 sujets"
Cela me paraît les 2 données intéressantes. Pour la distinction débats ouverts/clos, on a une autre idée avec @virgile-dev (mais qui change plus largement l'architecture de l'app) et le nombre de contributions/actions je ne sais pas, ça me parait moins motivant que le nombre de participants.

**Comment by virgile-dev** [comment]
J'aime bien l'idée que propose @valentinchaput

**Comment by moustachu** [comment]
Pour c'est en mode _quick & dirty_ avec juste le bouton sans les stats 😞

**Comment by virgile-dev** [comment]
Nickel pour le bouton mais je suis pas fan de comment ça rend niveau esthétique.
Est-ce qu'on en profiterait pas pour virer ces fonds géométriques tout dégueux pour passer à quelques choses plus sobre avec des couleurs unies?
