### ISSUE TITLE
Ajout de textes explicatifs devant les boutons d'interface

### ISSUE THREAD

**Issue by florent-andre** [democracy-os-fr/democracyos#56]
Serait-il possible d'ajouter les textes suivants devant les boutons d'interactions : 
-  précéder les boutons de vote d’une question, et ajouter quelques mots sur la possibilité de contribution, quelque chose qui pourrait être : « Êtes-vous d’accord avec l’objet de cet article et sa formulation ? » OUI, NON, abstention. 
- ajouter au dessus du bouton "ajouter une contribution" : « Si vous souhaitez ajouter une contribution sur l’objet de cet article et motiver votre choix, cliquez sur « Ajouter une contribution ».

**Comment by SumiSaintAuguste** [comment]
Pour le point 2: "cliquez ici:" plutôt que "cliquez sur 'Ajouter une contribuion'" (vu que le bouton sera juste en-dessous)
