### ISSUE TITLE
Correction orthographiques

### ISSUE THREAD

**Issue by florent-andre** [democracy-os-fr/democracyos#57]
* Page de confirmation d’inscription : corriger pour un accent aigu : 
![image004](https://cloud.githubusercontent.com/assets/837462/16767971/5084caca-4842-11e6-8e8f-aa5a7ae79e73.jpg)

* Mail de confirmation d ‘inscription : 
 * une majuscule sur le "l" de « L’équipe » 
 * un point-virgule et un s et une virgule pour la phrase qui suit.
![image008](https://cloud.githubusercontent.com/assets/837462/16768012/8bb3eb76-4842-11e6-9bc8-b579e0e0fb11.jpg)

**Comment by moustachu** [comment]
Fixed !
