### ISSUE TITLE
Disposer d'une page de "communication" sur les consultation

### ISSUE THREAD

**Issue by florent-andre** [democracy-os-fr/democracyos#59]
L'idée serait de pouvoir ajouter une page de présentation / explication / communication, plus fournie et détaillée autour de la consultation.

**Comment by virgile-dev** [comment]
Une nouvelle home a été mise en place lorsque la variable multiforum est activée. il suffit de modifier ce fichier https://github.com/democracy-os-fr/democracyos/blob/alt/agora/lib/layout/includes/intro.jade
