### ISSUE TITLE
[alt-agora] après l'ajout d'une règle, catégorie ou débat, afficher l'ensemble

### ISSUE THREAD

**Issue by arthur-koenig** [democracy-os-fr/democracyos#74]
Ré-afficher l'ensemble des règles après l'ajout d'une règle, de même pour les débats et catégories. Cela permet de bien montrer que l'élément a été ajouté et donne une vue d'ensemble. Envisager la même chose après une sauvegarde?

![saving](https://cloud.githubusercontent.com/assets/17574782/18273408/632e58f4-743d-11e6-813d-363f4f8a8960.png)

**Comment by virgile-dev** [comment]
1.  Lol la petite règle turdouille
2. En fait cette UX est pensée pour ajouter plein de règles à la volée en utilisant le bouton '+ Ajouter'. Qui faut l'avouer est bien pratique quand on doit rajouter des 'locations'
