### ISSUE TITLE
Le div qui contient le texte de bienvenue est trop étroit

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#76]
Une fois le formulaire d'inscription envoyé bien souvent le texte de confirmation fait faire des retours à la ligne un peu inutiles du genre : 
<img width="1433" alt="capture d ecran 2016-09-06 a 15 44 35" src="https://cloud.githubusercontent.com/assets/11473995/18275811/e5b3572e-7448-11e6-8352-e316a99b06a0.png">

Est-ce qu'on pourrait pas reprendre la vue qu'on utilise pour la confirmation email `/signup/validated` qui utilise un truc plus large?
<img width="1440" alt="capture d ecran 2016-09-06 a 15 48 04" src="https://cloud.githubusercontent.com/assets/11473995/18275995/80c1db8c-7449-11e6-941c-9968c3f87ad2.png">

**Comment by moustachu** [comment]
see PR #79
