### ISSUE TITLE
Récupérer le fix du double click pour se déconnecter

### ISSUE THREAD

**Issue by virgile-dev** [democracy-os-fr/democracyos#8]
Les argentins ont apporté un fix à ce problème on dirait https://github.com/DemocracyOS/democracyos/issues/1202. Merci de le rappatrier sur nos forks. Notamment : http://dos-agora-demo.herokuapp.com/

**Comment by virgile-dev** [comment]
J'ai toujours le même comportement qu'avant sur : http://dos-agora-demo.herokuapp.com/
Chez toi, ça marche correctement? @moustachu

**Comment by moustachu** [comment]
**OUI ÇA MARCHE**

avec des comptes Google, Facebook et normaux ... 

**sans séquence de clic et environnement clair je ne traite pas / plus ce bug*
